# DataFrame 인덱싱

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {"names" : ['aaa', 'aaa', 'bbb', 'ccc', 'ccc'],
       "year" : [2014, 2015, 2016, 2015, 2016],
       "points" : [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data, columns=['year', 'names', 'points', 'penalty'],
                 index = ['one', 'two', 'three', 'four', 'five'])

In [3]:
df

       year names  points penalty
one    2014   aaa     1.5     NaN
two    2015   aaa     1.7     NaN
three  2016   bbb     3.6     NaN
four   2015   ccc     2.4     NaN
five   2016   ccc     2.9     NaN

In [4]:
# year 열만 얻기
df['year']

one      2014
two      2015
three    2016
four     2015
five     2016
Name: year, dtype: int64

In [5]:
df.year

one      2014
two      2015
three    2016
four     2015
five     2016
Name: year, dtype: int64

In [6]:
# 두 개 이상의 열을 얻기
df[['year', 'points']]

       year  points
one    2014     1.5
two    2015     1.7
three  2016     3.6
four   2015     2.4
five   2016     2.9

In [7]:
# 값 넣기
df['penalty'] = 0.5

In [8]:
df

       year names  points  penalty
one    2014   aaa     1.5      0.5
two    2015   aaa     1.7      0.5
three  2016   bbb     3.6      0.5
four   2015   ccc     2.4      0.5
five   2016   ccc     2.9      0.5

In [9]:
# 행마다 다른 값 넣기
df['penalty'] = [0.1, 0.2, 0.3, 0.4, 0.5]

In [10]:
df

       year names  points  penalty
one    2014   aaa     1.5      0.1
two    2015   aaa     1.7      0.2
three  2016   bbb     3.6      0.3
four   2015   ccc     2.4      0.4
five   2016   ccc     2.9      0.5

In [11]:
# column 추가하고 값 넣기
df['zeros'] = np.arange(5)
df

       year names  points  penalty  zeros
one    2014   aaa     1.5      0.1      0
two    2015   aaa     1.7      0.2      1
three  2016   bbb     3.6      0.3      2
four   2015   ccc     2.4      0.4      3
five   2016   ccc     2.9      0.5      4

In [12]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [13]:
df['debt'] = val
df

       year names  points  penalty  zeros  debt
one    2014   aaa     1.5      0.1      0   NaN
two    2015   aaa     1.7      0.2      1  -1.2
three  2016   bbb     3.6      0.3      2   NaN
four   2015   ccc     2.4      0.4      3  -1.5
five   2016   ccc     2.9      0.5      4  -1.7

In [14]:
df['net_points'] = df['points'] - df['penalty']

In [15]:
df['high_points'] = df['net_points'] > 2.0

In [16]:
df

       year names  points  penalty  zeros  debt  net_points  high_points
one    2014   aaa     1.5      0.1      0   NaN         1.4        False
two    2015   aaa     1.7      0.2      1  -1.2         1.5        False
three  2016   bbb     3.6      0.3      2   NaN         3.3         True
four   2015   ccc     2.4      0.4      3  -1.5         2.0        False
five   2016   ccc     2.9      0.5      4  -1.7         2.4         True

In [17]:
# 기존의 열 삭제하기
del df['high_points']

In [18]:
del df['net_points']
del df['zeros']

In [19]:
df

       year names  points  penalty  debt
one    2014   aaa     1.5      0.1   NaN
two    2015   aaa     1.7      0.2  -1.2
three  2016   bbb     3.6      0.3   NaN
four   2015   ccc     2.4      0.4  -1.5
five   2016   ccc     2.9      0.5  -1.7

In [20]:
df.index.name = 'Order'
df.columns.name = 'Info'
df

Info   year names  points  penalty  debt
Order
one    2014   aaa     1.5      0.1   NaN
two    2015   aaa     1.7      0.2  -1.2
three  2016   bbb     3.6      0.3   NaN
four   2015   ccc     2.4      0.4  -1.5
five   2016   ccc     2.9      0.5  -1.7

In [21]:
# 행 제어하기
df[0:3]

Info   year names  points  penalty  debt
Order
one    2014   aaa     1.5      0.1   NaN
two    2015   aaa     1.7      0.2  -1.2
three  2016   bbb     3.6      0.3   NaN

In [23]:
df['two':'four']

Info   year names  points  penalty  debt
Order
two    2015   aaa     1.7      0.2  -1.2
three  2016   bbb     3.6      0.3   NaN
four   2015   ccc     2.4      0.4  -1.5

In [25]:
# 행선택하는 권장 방법 .loc(), .iloc()

In [26]:
df.loc['two'] # 인덱스 two 행의 전체 값 가져옴

Info
year       2015
names       aaa
points      1.7
penalty     0.2
debt       -1.2
Name: two, dtype: object

In [27]:
df.loc['two':'four']

Info   year names  points  penalty  debt
Order
two    2015   aaa     1.7      0.2  -1.2
three  2016   bbb     3.6      0.3   NaN
four   2015   ccc     2.4      0.4  -1.5

In [28]:
# columns --> 'points' 특정 값만 가져오기
df.loc['two':'four', 'points']

Order
two      1.7
three    3.6
four     2.4
Name: points, dtype: float64

In [29]:
df.loc[:, 'year']

Order
one      2014
two      2015
three    2016
four     2015
five     2016
Name: year, dtype: int64

In [30]:
# 두 개 이상의 열 검색
df.loc[:,['year', 'names']]

Info   year names
Order
one    2014   aaa
two    2015   aaa
three  2016   bbb
four   2015   ccc
five   2016   ccc

In [31]:
# 범위 인덱싱
df.loc['two':'four', ['year','names']]

Info   year names
Order
two    2015   aaa
three  2016   bbb
four   2015   ccc

In [32]:
df.loc['six', :] = [2017, 'ddd', 3.3, 0.6, -1.3]
df

Info     year names  points  penalty  debt
Order
one    2014.0   aaa     1.5      0.1   NaN
two    2015.0   aaa     1.7      0.2  -1.2
three  2016.0   bbb     3.6      0.3   NaN
four   2015.0   ccc     2.4      0.4  -1.5
five   2016.0   ccc     2.9      0.5  -1.7
six    2017.0   ddd     3.3      0.6  -1.3

In [33]:
# .iloc는 numpy 방식으로 (행/열 자리값으로) 값을 가져올 때 사용

In [34]:
df.iloc[3]

Info
year       2015.0
names         ccc
points        2.4
penalty       0.4
debt         -1.5
Name: four, dtype: object

In [35]:
df.iloc[0:3, 0:2]

Info     year names
Order
one    2014.0   aaa
two    2015.0   aaa
three  2016.0   bbb

In [36]:
# 행과 열의 벙위를 별도 지정해서 인덱싱
df.iloc[[0,1,3], [1,2]]

Info  names  points
Order
one     aaa     1.5
two     aaa     1.7
four    ccc     2.4

In [37]:
df.iloc[:, 1:4]

Info  names  points  penalty
Order
one     aaa     1.5      0.1
two     aaa     1.7      0.2
three   bbb     3.6      0.3
four    ccc     2.4      0.4
five    ccc     2.9      0.5
six     ddd     3.3      0.6

In [39]:
# 값 하나만 가져오기
df.iloc[1,1]

'aaa'

# 불리언 인덱싱

In [41]:
# year의 2014년보다 큰 값 찾기
df['year'] > 2014

Order
one      False
two       True
three     True
four      True
five      True
six       True
Name: year, dtype: bool

In [42]:
df

Info     year names  points  penalty  debt
Order
one    2014.0   aaa     1.5      0.1   NaN
two    2015.0   aaa     1.7      0.2  -1.2
three  2016.0   bbb     3.6      0.3   NaN
four   2015.0   ccc     2.4      0.4  -1.5
five   2016.0   ccc     2.9      0.5  -1.7
six    2017.0   ddd     3.3      0.6  -1.3

In [43]:
add = df['year'] > 2014
df['add'] = add
df.loc[:]

Info     year names  points  penalty  debt    add
Order
one    2014.0   aaa     1.5      0.1   NaN  False
two    2015.0   aaa     1.7      0.2  -1.2   True
three  2016.0   bbb     3.6      0.3   NaN   True
four   2015.0   ccc     2.4      0.4  -1.5   True
five   2016.0   ccc     2.9      0.5  -1.7   True
six    2017.0   ddd     3.3      0.6  -1.3   True

In [44]:
df.loc[df['year'] > 2014, :]

Info     year names  points  penalty  debt   add
Order
two    2015.0   aaa     1.7      0.2  -1.2  True
three  2016.0   bbb     3.6      0.3   NaN  True
four   2015.0   ccc     2.4      0.4  -1.5  True
five   2016.0   ccc     2.9      0.5  -1.7  True
six    2017.0   ddd     3.3      0.6  -1.3  True

In [45]:
df.loc[df['names'] == 'ccc', ['names', 'points']]

Info  names  points
Order
four    ccc     2.4
five    ccc     2.9

In [47]:
df.loc[(df['points'] > 2) & (df['points'] < 3), :]

Info     year names  points  penalty  debt   add
Order
four   2015.0   ccc     2.4      0.4  -1.5  True
five   2016.0   ccc     2.9      0.5  -1.7  True

In [53]:
# 새로운 값으로 대입
df.loc[df['points'] > 3, 'penalty'] = 0
df

Info     year names  points  penalty  debt    add
Order
one    2014.0   aaa     1.5      0.1   NaN  False
two    2015.0   aaa     1.7      0.2  -1.2   True
three  2016.0   bbb     3.6      0.0   NaN   True
four   2015.0   ccc     2.4      0.4  -1.5   True
five   2016.0   ccc     2.9      0.5  -1.7   True
six    2017.0   ddd     3.3      0.0  -1.3   True