In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.random.randn(6,4))
df

          0         1         2         3
0  0.203090  0.032948  0.616649 -0.320209
1 -0.336441 -0.642565 -1.218456 -1.408394
2 -0.163932  0.748386  0.663127  0.886445
3  1.046218 -0.616958  1.330970 -0.582344
4 -1.829305  1.356695 -0.752323 -0.563445
5 -0.181510  0.872373  1.465756 -0.079840

In [4]:
df.columns = ['a','b','c','d']
df.index = pd.date_range('20250501', periods=6)

In [5]:
df.index

DatetimeIndex(['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04',
               '2025-05-05', '2025-05-06'],
              dtype='datetime64[ns]', freq='D')

In [6]:
df

                   a         b         c         d
2025-05-01  0.203090  0.032948  0.616649 -0.320209
2025-05-02 -0.336441 -0.642565 -1.218456 -1.408394
2025-05-03 -0.163932  0.748386  0.663127  0.886445
2025-05-04  1.046218 -0.616958  1.330970 -0.582344
2025-05-05 -1.829305  1.356695 -0.752323 -0.563445
2025-05-06 -0.181510  0.872373  1.465756 -0.079840

In [7]:
df['f'] = [1.0, np.nan, 3.5, 6.1, np.nan, 7.0]

In [8]:
df

                   a         b         c         d    f
2025-05-01  0.203090  0.032948  0.616649 -0.320209  1.0
2025-05-02 -0.336441 -0.642565 -1.218456 -1.408394  NaN
2025-05-03 -0.163932  0.748386  0.663127  0.886445  3.5
2025-05-04  1.046218 -0.616958  1.330970 -0.582344  6.1
2025-05-05 -1.829305  1.356695 -0.752323 -0.563445  NaN
2025-05-06 -0.181510  0.872373  1.465756 -0.079840  7.0

In [9]:
# NAN 제거하기
df.dropna(how='any')  # nan이 하나라도 포함된 경우 그 행을 삭제

                   a         b         c         d    f
2025-05-01  0.203090  0.032948  0.616649 -0.320209  1.0
2025-05-03 -0.163932  0.748386  0.663127  0.886445  3.5
2025-05-04  1.046218 -0.616958  1.330970 -0.582344  6.1
2025-05-06 -0.181510  0.872373  1.465756 -0.079840  7.0

In [10]:
df.dropna(how='all')  # nan이 행 전체에 있을 경우, 그 행을 삭제한다.

                   a         b         c         d    f
2025-05-01  0.203090  0.032948  0.616649 -0.320209  1.0
2025-05-02 -0.336441 -0.642565 -1.218456 -1.408394  NaN
2025-05-03 -0.163932  0.748386  0.663127  0.886445  3.5
2025-05-04  1.046218 -0.616958  1.330970 -0.582344  6.1
2025-05-05 -1.829305  1.356695 -0.752323 -0.563445  NaN
2025-05-06 -0.181510  0.872373  1.465756 -0.079840  7.0

In [11]:
# nan 값 대체하기
df.fillna(value=5.0)

                   a         b         c         d    f
2025-05-01  0.203090  0.032948  0.616649 -0.320209  1.0
2025-05-02 -0.336441 -0.642565 -1.218456 -1.408394  5.0
2025-05-03 -0.163932  0.748386  0.663127  0.886445  3.5
2025-05-04  1.046218 -0.616958  1.330970 -0.582344  6.1
2025-05-05 -1.829305  1.356695 -0.752323 -0.563445  5.0
2025-05-06 -0.181510  0.872373  1.465756 -0.079840  7.0

In [12]:
# 불리언 마스크로 값을 제어하기
df.isnull()

                a      b      c      d      f
2025-05-01  False  False  False  False  False
2025-05-02  False  False  False  False   True
2025-05-03  False  False  False  False  False
2025-05-04  False  False  False  False  False
2025-05-05  False  False  False  False   True
2025-05-06  False  False  False  False  False

In [13]:
# nan이 있는 행 얻어오기
df.loc[df.isnull()['f'], :]

                   a         b         c         d   f
2025-05-02 -0.336441 -0.642565 -1.218456 -1.408394 NaN
2025-05-05 -1.829305  1.356695 -0.752323 -0.563445 NaN

In [14]:
# 인덱스 기준으로 행삭제
pd.to_datetime('20250505')

Timestamp('2025-05-05 00:00:00')

In [15]:
df.drop(pd.to_datetime('20250505'))

                   a         b         c         d    f
2025-05-01  0.203090  0.032948  0.616649 -0.320209  1.0
2025-05-02 -0.336441 -0.642565 -1.218456 -1.408394  NaN
2025-05-03 -0.163932  0.748386  0.663127  0.886445  3.5
2025-05-04  1.046218 -0.616958  1.330970 -0.582344  6.1
2025-05-06 -0.181510  0.872373  1.465756 -0.079840  7.0

In [17]:
# 인덱스 기준으로 두 개 이상의 행 삭제하기
df.drop([pd.to_datetime('20250504'), pd.to_datetime('20250506')])

                   a         b         c         d    f
2025-05-01  0.203090  0.032948  0.616649 -0.320209  1.0
2025-05-02 -0.336441 -0.642565 -1.218456 -1.408394  NaN
2025-05-03 -0.163932  0.748386  0.663127  0.886445  3.5
2025-05-05 -1.829305  1.356695 -0.752323 -0.563445  NaN

In [18]:
# 열 삭제하기
df.drop('f', axis=1)

                   a         b         c         d
2025-05-01  0.203090  0.032948  0.616649 -0.320209
2025-05-02 -0.336441 -0.642565 -1.218456 -1.408394
2025-05-03 -0.163932  0.748386  0.663127  0.886445
2025-05-04  1.046218 -0.616958  1.330970 -0.582344
2025-05-05 -1.829305  1.356695 -0.752323 -0.563445
2025-05-06 -0.181510  0.872373  1.465756 -0.079840

In [19]:
df.drop(['b', 'd'], axis=1)

                   a         c    f
2025-05-01  0.203090  0.616649  1.0
2025-05-02 -0.336441 -1.218456  NaN
2025-05-03 -0.163932  0.663127  3.5
2025-05-04  1.046218  1.330970  6.1
2025-05-05 -1.829305 -0.752323  NaN
2025-05-06 -0.181510  1.465756  7.0

In [20]:
data = [[1.40, np.nan],
       [7.10, -4.5],
       [np.nan, np.nan],
       [0.75, -1.3]]

In [21]:
data

[[1.4, nan], [7.1, -4.5], [nan, nan], [0.75, -1.3]]

In [22]:
df = pd.DataFrame(data, columns = ['one', 'two'], index = ['a','b','c','d'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [23]:
# 행방향으로 열의 합을 계산(nan은 배제하고 계산)
df.sum(axis=0)

one    9.25
two   -5.80
dtype: float64

In [24]:
# 열방향으로 각 행의 합을 계산
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [25]:
# 특정 열 또는 행의 값 계산
df['one'].sum()

np.float64(9.25)

In [26]:
df.loc['b'].sum()

np.float64(2.5999999999999996)

In [27]:
df.mean(axis=0)['two']

np.float64(-2.9)

In [28]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [29]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [30]:
one_mean = df.mean(axis=0)['one']
two_min = df.min(axis=0)['two']

In [32]:
df['one'] = df['one'].fillna(value=one_mean)
df['two'] = df['two'].fillna(value=two_min)
df

        one  two
a  1.400000 -4.5
b  7.100000 -4.5
c  3.083333 -4.5
d  0.750000 -1.3

In [34]:
# 상관계수 구하기
df2 = pd.DataFrame(np.random.randn(6,4),
                  columns = ['a','b','c','d'],
                  index = pd.date_range('20250101', periods=6))
df2

                   a         b         c         d
2025-01-01 -0.104947 -0.684303 -0.879715 -1.043275
2025-01-02  0.628476  1.318007 -0.664985 -0.618406
2025-01-03 -0.979402  0.569672 -1.435886 -0.364890
2025-01-04  1.936496 -0.597618  0.393210 -0.449378
2025-01-05  0.900237 -0.614591  0.851281 -1.439017
2025-01-06 -0.306810  0.954314 -3.111009 -0.377615

In [35]:
# a열과 b열의 상관계수 산출하기 (피어슨상관계수로 계산)
df2['b'].corr(df2['c'])

np.float64(-0.6417239086908254)

In [36]:
df2.corr()

          a         b         c         d
a  1.000000 -0.430219  0.722275 -0.217520
b -0.430219  1.000000 -0.641724  0.593655
c  0.722275 -0.641724  1.000000 -0.600506
d -0.217520  0.593655 -0.600506  1.000000

In [37]:
# 정렬 및 기타 함수
dates = df2.index
random_dates = np.random.permutation(dates)
df2 = df2.reindex(index=random_dates, columns=['a','b','c','d'])
df2

                   a         b         c         d
2025-01-02  0.628476  1.318007 -0.664985 -0.618406
2025-01-04  1.936496 -0.597618  0.393210 -0.449378
2025-01-03 -0.979402  0.569672 -1.435886 -0.364890
2025-01-01 -0.104947 -0.684303 -0.879715 -1.043275
2025-01-05  0.900237 -0.614591  0.851281 -1.439017
2025-01-06 -0.306810  0.954314 -3.111009 -0.377615

In [38]:
# index 기준으로 오름차순 정렬
df2.sort_index(axis=0)

                   a         b         c         d
2025-01-01 -0.104947 -0.684303 -0.879715 -1.043275
2025-01-02  0.628476  1.318007 -0.664985 -0.618406
2025-01-03 -0.979402  0.569672 -1.435886 -0.364890
2025-01-04  1.936496 -0.597618  0.393210 -0.449378
2025-01-05  0.900237 -0.614591  0.851281 -1.439017
2025-01-06 -0.306810  0.954314 -3.111009 -0.377615

In [39]:
# 컬럼 기준으로 오름차순 정렬
df2.sort_index(axis=1)

                   a         b         c         d
2025-01-02  0.628476  1.318007 -0.664985 -0.618406
2025-01-04  1.936496 -0.597618  0.393210 -0.449378
2025-01-03 -0.979402  0.569672 -1.435886 -0.364890
2025-01-01 -0.104947 -0.684303 -0.879715 -1.043275
2025-01-05  0.900237 -0.614591  0.851281 -1.439017
2025-01-06 -0.306810  0.954314 -3.111009 -0.377615

In [40]:
# 컬럼 기준으로 내림차순 정렬
df2.sort_index(axis=0, ascending=False)

                   a         b         c         d
2025-01-06 -0.306810  0.954314 -3.111009 -0.377615
2025-01-05  0.900237 -0.614591  0.851281 -1.439017
2025-01-04  1.936496 -0.597618  0.393210 -0.449378
2025-01-03 -0.979402  0.569672 -1.435886 -0.364890
2025-01-02  0.628476  1.318007 -0.664985 -0.618406
2025-01-01 -0.104947 -0.684303 -0.879715 -1.043275

In [41]:
# value 기준으로 오름차순 정렬
df2.sort_values(by='a')

                   a         b         c         d
2025-01-03 -0.979402  0.569672 -1.435886 -0.364890
2025-01-06 -0.306810  0.954314 -3.111009 -0.377615
2025-01-01 -0.104947 -0.684303 -0.879715 -1.043275
2025-01-02  0.628476  1.318007 -0.664985 -0.618406
2025-01-05  0.900237 -0.614591  0.851281 -1.439017
2025-01-04  1.936496 -0.597618  0.393210 -0.449378

In [42]:
# value 기준으로 내림차순 정렬
df2.sort_values(by='b', ascending=False)

                   a         b         c         d
2025-01-02  0.628476  1.318007 -0.664985 -0.618406
2025-01-06 -0.306810  0.954314 -3.111009 -0.377615
2025-01-03 -0.979402  0.569672 -1.435886 -0.364890
2025-01-04  1.936496 -0.597618  0.393210 -0.449378
2025-01-05  0.900237 -0.614591  0.851281 -1.439017
2025-01-01 -0.104947 -0.684303 -0.879715 -1.043275

In [48]:
df2['e'] = np.random.randint(6.0, size=6)
df2['f'] = ['alpha','beta','gamma','gamma','alpha','gamma']

In [51]:
df2['f'].unique()

array(['alpha', 'beta', 'gamma'], dtype=object)

In [2]:
add = lambda x, y : x + y

In [3]:
print(add(3, 5))

8

In [4]:
df3 = pd.DataFrame(np.random.randn(4,3),
                  index=['Seaoul','Incheon','Busan','Daegu'],
                  columns = ['b','d','e'])

In [5]:
df3

                b         d         e
Seaoul   0.907681  1.302329 -1.071414
Incheon  0.841345 -0.009490  0.647843
Busan    0.179752 -0.847540  0.273934
Daegu    0.504340 -1.776247 -0.379729

In [6]:
func = lambda x: x.max() - x.min()   # x.max : 행 또는 열의 최대값, x.min : 행 또는 열의 최소값

In [9]:
df3.apply(func, axis=0) # 행방향으로 열 별로 lambda 함수 값을 계산

b    0.727930
d    3.078576
e    1.719257
dtype: float64

In [10]:
df3.apply(func, axis=1)  # 열방향으로 행 별로 lambda 함수 값을 계산

Seaoul     2.373742
Incheon    0.850834
Busan      1.121474
Daegu      2.280587
dtype: float64