In [1]:
import pandas as pd
import numpy as np

In [3]:
data = np.genfromtxt('./data/ratings.dat', delimiter='::', dtype=np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], shape=(1000209, 4))

In [4]:
data[:6, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268]])

In [5]:
data.shape

(1000209, 4)

In [8]:
names = pd.read_csv('./data/NationalNames.csv')

In [9]:
names

              Id       Name  Year Gender  Count
0              1       Mary  1880      F   7065
1              2       Anna  1880      F   2604
2              3       Emma  1880      F   2003
3              4  Elizabeth  1880      F   1939
4              5     Minnie  1880      F   1746
...          ...        ...   ...    ...    ...
1825428  1825429     Zykeem  2014      M      5
1825429  1825430     Zymeer  2014      M      5
1825430  1825431    Zymiere  2014      M      5
1825431  1825432      Zyran  2014      M      5
1825432  1825433      Zyrin  2014      M      5

[1825433 rows x 5 columns]

In [10]:
data = np.genfromtxt('./data/ratings.dat', delimiter= '::', dtype=np.int64)

In [11]:
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], shape=(1000209, 4))

In [12]:
names = pd.read_csv('./data/NationalNames.csv', header=0)

In [13]:
names

              Id       Name  Year Gender  Count
0              1       Mary  1880      F   7065
1              2       Anna  1880      F   2604
2              3       Emma  1880      F   2003
3              4  Elizabeth  1880      F   1939
4              5     Minnie  1880      F   1746
...          ...        ...   ...    ...    ...
1825428  1825429     Zykeem  2014      M      5
1825429  1825430     Zymeer  2014      M      5
1825430  1825431    Zymiere  2014      M      5
1825431  1825432      Zyran  2014      M      5
1825432  1825433      Zyrin  2014      M      5

[1825433 rows x 5 columns]

In [14]:
data = np.genfromtxt('./data/ratings.dat', delimiter='::', dtype=np.int64)

In [15]:
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], shape=(1000209, 4))

In [2]:
from pymongo import MongoClient