# 그래프 생성

In [4]:
import numpy as np
import pandas as pd

# 1.1) Subjects.csv 파일을 읽어 와서 'df'변수에 저장하기

In [5]:
df = pd.read_csv('./data/Subjects.csv')
df

    class name  kor  eng  math  science
0       1  aaa   67   87    90       98
1       1  bbb   45   45    56       98
2       1  ccc   95   59    96       88
3       1  ddd   65   94    89       98
4       1  eee   45   65    78       98
5       1  fff   78   76    98       89
6       2  ggg   87   67    65       56
7       2  hhh   89   98    78       78
8       2  iii  100   78    56       65
9       2  jjj   99   89    87       87
10      2  kkk   98   45    56       54
11      2  lll   65   89    87       78

# 1.2) df DataFrame에 '총점'과 '평균' 열을 추가하여 각 학생 별 총점, 평균 점수를 입력

In [8]:
df['Total'] = 0
df

    class name  kor  eng  math  science  Total
0       1  aaa   67   87    90       98      0
1       1  bbb   45   45    56       98      0
2       1  ccc   95   59    96       88      0
3       1  ddd   65   94    89       98      0
4       1  eee   45   65    78       98      0
5       1  fff   78   76    98       89      0
6       2  ggg   87   67    65       56      0
7       2  hhh   89   98    78       78      0
8       2  iii  100   78    56       65      0
9       2  jjj   99   89    87       87      0
10      2  kkk   98   45    56       54      0
11      2  lll   65   89    87       78      0

In [9]:
df['Avg'] = 0
df

    class name  kor  eng  math  science  Total  Avg
0       1  aaa   67   87    90       98      0    0
1       1  bbb   45   45    56       98      0    0
2       1  ccc   95   59    96       88      0    0
3       1  ddd   65   94    89       98      0    0
4       1  eee   45   65    78       98      0    0
5       1  fff   78   76    98       89      0    0
6       2  ggg   87   67    65       56      0    0
7       2  hhh   89   98    78       78      0    0
8       2  iii  100   78    56       65      0    0
9       2  jjj   99   89    87       87      0    0
10      2  kkk   98   45    56       54      0    0
11      2  lll   65   89    87       78      0    0

In [16]:
student_points = df[['kor', 'eng', 'math', 'science']]
student_points

    kor  eng  math  science
0    67   87    90       98
1    45   45    56       98
2    95   59    96       88
3    65   94    89       98
4    45   65    78       98
5    78   76    98       89
6    87   67    65       56
7    89   98    78       78
8   100   78    56       65
9    99   89    87       87
10   98   45    56       54
11   65   89    87       78

In [19]:
student_total = student_points.sum(axis=1)

In [20]:
student_total

0     342
1     244
2     338
3     346
4     286
5     341
6     275
7     343
8     299
9     362
10    253
11    319
dtype: int64

In [22]:
df['Total'] = student_total
df

    class name  kor  eng  math  science  Total  Avg
0       1  aaa   67   87    90       98    342    0
1       1  bbb   45   45    56       98    244    0
2       1  ccc   95   59    96       88    338    0
3       1  ddd   65   94    89       98    346    0
4       1  eee   45   65    78       98    286    0
5       1  fff   78   76    98       89    341    0
6       2  ggg   87   67    65       56    275    0
7       2  hhh   89   98    78       78    343    0
8       2  iii  100   78    56       65    299    0
9       2  jjj   99   89    87       87    362    0
10      2  kkk   98   45    56       54    253    0
11      2  lll   65   89    87       78    319    0

In [24]:
student_mean = student_points.mean(axis=1)
student_mean

0     85.50
1     61.00
2     84.50
3     86.50
4     71.50
5     85.25
6     68.75
7     85.75
8     74.75
9     90.50
10    63.25
11    79.75
dtype: float64

In [25]:
df['Avg'] = student_mean
df

    class name  kor  eng  math  science  Total    Avg
0       1  aaa   67   87    90       98    342  85.50
1       1  bbb   45   45    56       98    244  61.00
2       1  ccc   95   59    96       88    338  84.50
3       1  ddd   65   94    89       98    346  86.50
4       1  eee   45   65    78       98    286  71.50
5       1  fff   78   76    98       89    341  85.25
6       2  ggg   87   67    65       56    275  68.75
7       2  hhh   89   98    78       78    343  85.75
8       2  iii  100   78    56       65    299  74.75
9       2  jjj   99   89    87       87    362  90.50
10      2  kkk   98   45    56       54    253  63.25
11      2  lll   65   89    87       78    319  79.75

# 1.3) Class1반과 Class2반의 평균 점수를 각각 출력

In [26]:
student_class_avg = df[['class', 'Avg']]
student_class_avg

    class    Avg
0       1  85.50
1       1  61.00
2       1  84.50
3       1  86.50
4       1  71.50
5       1  85.25
6       2  68.75
7       2  85.75
8       2  74.75
9       2  90.50
10      2  63.25
11      2  79.75

In [27]:
student_class1_avg = student_class_avg.loc[student_class_avg['class'] == 1, ['class', 'Avg']]
student_class1_avg

   class    Avg
0      1  85.50
1      1  61.00
2      1  84.50
3      1  86.50
4      1  71.50
5      1  85.25

In [28]:
student_class2_avg = student_class_avg.loc[student_class_avg['class'] == 2, ['class', 'Avg']]
student_class2_avg

    class    Avg
6       2  68.75
7       2  85.75
8       2  74.75
9       2  90.50
10      2  63.25
11      2  79.75

# 1.4) Class1반과 Class2반 두 집단의 차이가 유의한지 p value 값 계산하기

# 1.5) class별 과목 분석

In [32]:
student_class1 = df.loc[df['class'] == 1, :]
student_class1

   class name  kor  eng  math  science  Total    Avg
0      1  aaa   67   87    90       98    342  85.50
1      1  bbb   45   45    56       98    244  61.00
2      1  ccc   95   59    96       88    338  84.50
3      1  ddd   65   94    89       98    346  86.50
4      1  eee   45   65    78       98    286  71.50
5      1  fff   78   76    98       89    341  85.25

In [34]:
student_class2 = df.loc[df['class'] == 2, :]
student_class2

    class name  kor  eng  math  science  Total    Avg
6       2  ggg   87   67    65       56    275  68.75
7       2  hhh   89   98    78       78    343  85.75
8       2  iii  100   78    56       65    299  74.75
9       2  jjj   99   89    87       87    362  90.50
10      2  kkk   98   45    56       54    253  63.25
11      2  lll   65   89    87       78    319  79.75

In [35]:
student_class1_category_sum = student_class1.sum(axis=0)
student_class1_category_sum

class                       6
name       aaabbbcccdddeeefff
kor                       395
eng                       426
math                      507
science                   569
Total                    1897
Avg                    474.25
dtype: object

In [ ]:
student_class1_category_sum =